version: '3'
services:
    shop-website-angular:
        build:
            context: .
            dockerfile: Dockerfile-dev
        container_name: ever-shop
        networks:
            - shop-website-angular
        ports:
            - '3000:3000'
        environment:
            - HOST=0.0.0.0
        command: npm run start
networks:
    shop-website-angular:
        driver: bridge
