branch-defaults:
    master:
        environment: ever-merchants-env
environment-defaults:
    ever-api-env:
        branch: null
        repository: null
global:
    application_name: merchants
    default_ec2_keyname: ever
    default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
    default_region: us-east-1
    profile: null
    sc: git
